### ISSUE TITLE
CheckAnalyse recommends when AutoSplitTasks is True

### ISSUE THREAD

**Issue by lewisr20** [DavidPratten/PMQu#14]
CheckAnalyse recommends changing the setting when AutoSplitTasks is True however this should recommend to make it true when the setting is False.

Currently:
```
    If ActiveProject.AutoSplitTasks Then
        LogErrorConfig testNo, settings36(8)
    End If
```
Should be:
```
    If Not ActiveProject.AutoSplitTasks Then
        LogErrorConfig testNo, settings36(8)
    End If
```
Same issue with ManuallyScheduledTasksAutoRespectLinks and HonorConstraints unless I'm reading it wrong and you want to recommend turning off these features?

**Comment by DavidPratten** [comment]
Yes, the intent is to recommend that these settings be off. These two checks can be disabled on a per project basis.  

David

**Comment by lewisr20** [comment]
Thanks. These appear to be default settings so thought it may have been an error! Have code to contribute and will share once I've tested some more as I'm building schedule quality tests to comply with DCMA and NASA standards and want to include them in the report,

**Comment by DavidPratten** [comment]
Sounds good.  Let me know when you have something to share!

David
